# Aula 10 - ExercÃ­cio em aula

In [33]:
!pip install pandas numpy scipy seaborn matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\guino\appdata\roaming\python\python312\site-packages (2.2.2)
Requirement already satisfied: numpy in c:\users\guino\appdata\roaming\python\python312\site-packages (2.1.1)
Requirement already satisfied: scipy in c:\users\guino\appdata\roaming\python\python312\site-packages (1.14.1)
Requirement already satisfied: seaborn in c:\users\guino\appdata\roaming\python\python312\site-packages (0.13.2)
Requirement already satisfied: matplotlib in c:\users\guino\appdata\roaming\python\python312\site-packages (3.9.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\guino\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\guino\appdata\roaming\python\python312\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\guino\appdata\roaming\python\python312\site-packages (from pandas) (2024.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\guino\appdata\roaming\python\python312\site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in c:\users\guino\appdata\roaming\python\python312\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\guino\appdata\roaming\python\python312\site-packages (from matplotlib) (4.54.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\guino\appdata\roaming\python\python312\site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: packaging>=20.0 in c:\users\guino\appdata\roaming\python\python312\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\guino\appdata\roaming\python\python312\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\guino\appdata\roaming\python\python312\site-packages (from matplotlib) (3.1.4)
Requirement already satisfied: six>=1.5 in c:\users\guino\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [34]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as plt
import os
os.getcwd()

'c:\\Users\\guino\\OneDrive\\Documents\\Unesp\\projects\\DS_Unesp\\Work_Git\\GuilhermeGumiero\\WorkGit\\Aula 10'

In [35]:
df = pd.read_csv('c:\\Users\\guino\\OneDrive\\Documents\\Unesp\\projects\\DS_Unesp\\Datasets\\lanchonete.csv')

df

    Entrega_ID  Minutos  Segundos
0            1       35        57
1            2       31        58
2            3       38        49
3            4       46        14
4            5       30         8
5            6       30         8
6            7       38        41
7            8       35         9
8            9       32        22
9           10       32        22
10          11       40        18
11          12       34         9
12          13       24        20
13          14       31        58
14          15       34        55
15          16       34        55
16          17       28        28
17          18       27         5
18          19       34         3
19          20       31        54
20          21       28        58
21          22       27         4
22          23       27         4
23          24       30        27
24          25       36        13
25          26       40        24
26          27       38        15
27          28       36        45
28          29       30         8
29          30       29        27

In [36]:
# Calcular o tempo total em minutos e selecionar apenas as colunas 'id' e 'tempo_total_minutos'
df_transformado = df.assign(tempo_total_minutos=df['Minutos'] + df['Segundos'] / 60).round(2)[['Entrega_ID', 'tempo_total_minutos']]

# Definir a mÃ©dia esperada foi dada (H0: mÃ©dia = 30 horas)
media_esperada = 30

# Temos que a mÃ©dia observada em Ha = 33.29
df_transformado['tempo_total_minutos'].mean()

# Realizar o teste t para amostras Ãºnicas
t_stat, p_val = stats.ttest_1samp(df_transformado['tempo_total_minutos'], media_esperada)

# Exibir os resultados
print(f"EstatÃ­stica t: {t_stat}")
print(f"p-valor: {p_val}")

# InterpretaÃ§Ã£o do p-valor
alpha = 0.05 # Escolhido por nÃ³s
if p_val < alpha:
    print("Rejeitamos a hipÃ³tese nula (Hâ). A mÃ©dia das horas trabalhadas Ã© significativamente diferente de 40 horas.")
else:
    print("Falhamos em rejeitar a hipÃ³tese nula (Hâ). A mÃ©dia das horas trabalhadas nÃ£o Ã© significativamente diferente de 40 horas.")

EstatÃ­stica t: 3.700234721618818
p-valor: 0.0008969111577070808
Rejeitamos a hipÃ³tese nula (Hâ). A mÃ©dia das horas trabalhadas Ã© significativamente diferente de 40 horas.